version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: schwob-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schwob_aufm_sattl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - schwob-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: schwob-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/schwob_aufm_sattl
      - SECRET_KEY=yoursecretkey
    volumes:
      - ./backend:/app
      - ./media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - schwob-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: schwob-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - schwob-network
    command: npm run dev

networks:
  schwob-network:
    driver: bridge

volumes:
  postgres_data:
